export const planets = [
  "Alderaan",
  "Yavin IV",
  "Hoth",
  "Dagobah",
  "Bespin",
  "Endor",
  "Naboo",
  "Coruscant",
  "Kamino",
  "Geonosis",
  "Utapau",
  "Mustafar",
  "Kashyyyk",
  "Polis Massa",
  "Mygeeto",
  "Felucia",
  "Cato Neimoidia",
  "Saleucami",
  "Stewjon",
  "Eriadu",
  "Corellia",
  "Rodia",
  "Nal Hutta",
  "Dantooine",
  "Bestine IV",
  "Ord Mantell",
  "unknown",
  "Trandosha",
  "Socorro",
  "Mon Cala",
  "Chandrila",
  "Sullust",
  "Toydaria",
  "Malastare",
  "Dathomir",
  "Ryloth",
  "Aleen Minor",
  "Vulpter",
  "Troiken",
  "Tund",
  "Haruun Kal",
  "Cerea",
  "Glee Anselm",
  "Iridonia",
  "Tholoth",
  "Iktotch",
  "Quermia",
  "Dorin",
  "Champala",
  "Mirial",
];

export const characters = [
  "Luke Skywalker",
  "C-3PO",
  "R2-D2",
  "Darth Vader",
  "Leia Organa",
  "Owen Lars",
  "Beru Whitesun lars",
  "R5-D4",
  "Biggs Darklighter",
  "Obi-Wan Kenobi",
  "Anakin Skywalker",
  "Wilhuff Tarkin",
  "Chewbacca",
  "Han Solo",
  "Greedo",
  "Jabba Desilijic Tiure",
  "Wedge Antilles",
  "Jek Tono Porkins",
  "Yoda",
  "Palpatine",
  "Boba Fett",
  "IG-88",
  "Bossk",
  "Lando Calrissian",
  "Lobot",
  "Ackbar",
  "Mon Mothma",
  "Arvel Crynyd",
  "Wicket Systri Warric",
  "Nien Nunb",
  "Qui-Gon Jinn",
  "Nute Gunray",
  "Finis Valorum",
  "Jar Jar Binks",
  "Roos Tarpals",
  "Rugor Nass",
  "Ric Olié",
  "Watto",
  "Sebulba",
  "Quarsh Panaka",
];
